import Head from 'next/head';
import OrderForm, { OrderFormData } from '../components/OrderForm/OrderForm';
import router from 'next/router';
import api from '@/services/api';
import { Order } from '@/model/types';
import { useState } from 'react';
import Snackbar from '@mui/material/Snackbar';
import MuiAlert, { AlertProps } from '@mui/material/Alert';

export default function Home() {
  const [showMessage, setShowMessage] = useState<string | null>(null);

  const handleSubmit = async (data: OrderFormData) => {
    try {
      const response = await api.post<
        | { Order: Order; Message?: undefined }
        | { Message: string; Order?: undefined }
      >('/orders/create', data);

      if (response.data.Order) {
        router.push(`/${response.data.Order.ID}`);
      } else {
        setShowMessage(response.data.Message);
      }
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <>
      <Head>
        <title>Orders App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <OrderForm onSubmit={handleSubmit} />
      <Snackbar
        open={Boolean(showMessage)}
        autoHideDuration={3000}
        onClose={() => setShowMessage(null)}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
      >
        <MuiAlert onClose={() => setShowMessage(null)} severity='error'>
          {showMessage}
        </MuiAlert>
      </Snackbar>
      ;
    </>
  );
}
