import Head from 'next/head';
import OrderForm, { OrderFormData } from '../components/OrderForm/OrderForm';
import router from 'next/router';
import api from '@/services/api';
import { Order } from '@/model/types';
import { useState } from 'react';

export default function Home() {
  const handleSubmit = async (data: OrderFormData) => {
    try {
      const response = await api.post<{ Order: Order }>('/orders/create', data);

      router.push(`/${response.data.Order.ID}`);
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <>
      <Head>
        <title>Orders App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <OrderForm onSubmit={handleSubmit} />
    </>
  );
}
